// NEW KEYS TO ADD TO 'en' MAP:
      'activity_log_clear_activity_log': 'Clear Activity Log?',
      'activity_log_clear_activity_log_2': 'Clear Activity Log?',
      'activity_log_this_will_permanently_delete_all_logged_': 'This will permanently delete all logged events.',
      'activity_log_this_will_permanently_delete_all_logged__2': 'This will permanently delete all logged events.',
      'activity_log_cancel': 'Cancel',
      'activity_log_clear': 'Clear',
      'add_device_flow_debug_log': 'Debug Log',
      'add_device_flow_log_copied_to_clipboard': 'Log copied to clipboard',
      'add_device_flow_log_copied_to_clipboard_2': 'Log copied to clipboard',
      'add_device_flow_copy': 'Copy',
      'add_device_flow_share': 'Share',
      'add_device_flow_wifi_network_name_ssid': 'WiFi Network Name (SSID)',
      'add_device_flow_password': 'Password',
      'add_device_flow_open_app_settings': 'Open App Settings',
      'add_device_flow_password_2': 'Password',
      'add_device_flow_save_wifi_for_future_devices': 'Save WiFi for future devices',
      'add_device_flow_wrong_network': 'Wrong Network?',
      'add_device_flow_wrong_network_2': 'Wrong Network?',
      'add_device_flow_cancel': 'Cancel',
      'add_device_flow_continue_anyway': 'Continue Anyway',
      'add_device_flow_device_name_eg_hallway_light': 'Device Name (e.g. Hallway Light)',
      'add_device_flow_edit_device_name': 'Edit Device Name',
      'add_device_flow_edit_device_name_2': 'Edit Device Name',
      'add_device_flow_enter_device_name': 'Enter device name',
      'add_device_flow_cancel_2': 'Cancel',
      'add_device_flow_save': 'Save',
      'add_device_flow_failed_to_update_device_name_e': 'Failed to update device name: $e',
      'add_device_flow_failed_to_update_device_name_e_2': 'Failed to update device name: $e',
      'add_device_flow_choose_room': 'Choose Room',
      'add_device_flow_choose_room_2': 'Choose Room',
      'add_device_flow_no_room': 'No Room',
      'add_device_flow_no_room_2': 'No Room',
      'add_device_flow_place_device_in_the_main_area': 'Place device in the main area',
      'add_device_flow_place_device_in_the_main_area_2': 'Place device in the main area',
      'add_device_flow_cancel_3': 'Cancel',
      'add_device_flow_unable_to_move_device_please_try_again': 'Unable to move device. Please try again.',
      'add_device_flow_unable_to_move_device_please_try_again_2': 'Unable to move device. Please try again.',
      'add_device_flow_network_issue': 'Network Issue',
      'add_device_flow_check_your_wifi_connection': '• Check your Wi-Fi connection',
      'add_device_flow_try_turning_wifi_off_and_on': '• Try turning Wi-Fi off and on',
      'add_device_flow_check_if_other_apps_can_access_the_inter': '• Check if other apps can access the internet',
      'add_device_flow_cancel_4': 'Cancel',
      'add_device_flow_wifi_settings': 'Wi-Fi Settings',
      'add_device_flow_retry': 'Retry',
      'add_device_flow_device_setup_error': 'Device Setup Error',
      'add_device_flow_try_the_setup_process_again': '• Try the setup process again',
      'add_device_flow_reset_the_device_and_start_over': '• Reset the device and start over',
      'add_device_flow_check_if_the_device_is_already_added': '• Check if the device is already added',
      'add_device_flow_contact_support_if_the_issue_persists': '• Contact support if the issue persists',
      'add_device_flow_cancel_5': 'Cancel',
      'add_device_flow_try_again': 'Try Again',
      'add_device_flow_wifi_settings_2': 'Wi-Fi Settings',
      'add_device_flow_wifi_settings_3': 'Wi-Fi Settings',
      'add_timer_window_min': '$_window min',
      'devices_failed_to_load_devices_e': 'Failed to load devices: $e',
      'devices_failed_to_load_devices_e_2': 'Failed to load devices: $e',
      'devices_close': 'Close',
      'devices_stop': 'Stop',
      'devices_open': 'Open',
      'devices_connection_lost_please_check_your_networ': 'Connection lost. Please check your network.',
      'devices_failed_to_control_shutter_etostring': 'Failed to control shutter: ${e.toString()}',
      'devices_failed_to_control_shutter_etostring_2': 'Failed to control shutter: ${e.toString()}',
      'devices_connection_lost_please_check_your_networ_2': 'Connection lost. Please check your network.',
      'devices_failed_to_control_device_etostring': 'Failed to control device: ${e.toString()}',
      'devices_failed_to_control_device_etostring_2': 'Failed to control device: ${e.toString()}',
      'devices_add_device': 'Add Device',
      'devices_add_device_2': 'Add Device',
      'devices_hbot_device': 'HBOT Device',
      'devices_hbot_device_2': 'HBOT Device',
      'devices_add_hbot_device_via_wifi': 'Add HBOT device via Wi-Fi',
      'devices_add_hbot_device_via_wifi_2': 'Add HBOT device via Wi-Fi',
      'devices_cancel': 'Cancel',
      'devices_delete_device': 'Delete Device',
      'devices_delete': 'Delete',
      'devices_device': 'Device ',
      'devices_device_2': 'Device ',
      'devices_delete_failed': 'Delete Failed',
      'device_timers_delete_timer': 'Delete Timer',
      'device_timers_delete_timer_2': 'Delete Timer',
      'device_timers_cancel': 'Cancel',
      'device_timers_delete': 'Delete',
      'device_timers_failed_to_update_timer_e': 'Failed to update timer: $e',
      'device_timers_failed_to_update_timer_e_2': 'Failed to update timer: $e',
      'device_timers_widgetdevicename_timers': '${widget.device.name} Timers',
      'device_timers_add_timer': 'Add Timer',
      'feedback_send_feedback': 'Send Feedback',
      'feedback_send_feedback_2': 'Send Feedback',
      'feedback_send_via_email': 'Send via Email',
      'feedback_send_via_whatsapp': 'Send via WhatsApp',
      'help_center_help_center': 'Help Center',
      'help_center_help_center_2': 'Help Center',
      'homes_failed_to_load_homes_e': 'Failed to load homes: $e',
      'homes_failed_to_load_homes_e_2': 'Failed to load homes: $e',
      'homes_please_enter_a_home_name': 'Please enter a home name',
      'homes_please_enter_a_home_name_2': 'Please enter a home name',
      'homes_home': 'Home ',
      'homes_home_2': 'Home ',
      'homes_failed_to_create_home_e': 'Failed to create home: $e',
      'homes_failed_to_create_home_e_2': 'Failed to create home: $e',
      'homes_please_enter_a_home_name_3': 'Please enter a home name',
      'homes_please_enter_a_home_name_4': 'Please enter a home name',
      'homes_failed_to_update_home_e': 'Failed to update home: $e',
      'homes_failed_to_update_home_e_2': 'Failed to update home: $e',
      'homes_home_3': 'Home ',
      'homes_home_4': 'Home ',
      'homes_failed_to_delete_home_e': 'Failed to delete home: $e',
      'homes_failed_to_delete_home_e_2': 'Failed to delete home: $e',
      'homes_create_new_home': 'Create New Home',
      'homes_create_new_home_2': 'Create New Home',
      'homes_home_name': 'Home Name',
      'homes_eg_my_house_office_etc': 'e.g., My House, Office, etc.',
      'homes_cancel': 'Cancel',
      'homes_create': 'Create',
      'homes_edit_home': 'Edit Home',
      'homes_edit_home_2': 'Edit Home',
      'homes_home_name_2': 'Home Name',
      'homes_eg_my_house_office_etc_2': 'e.g., My House, Office, etc.',
      'homes_cancel_2': 'Cancel',
      'homes_save': 'Save',
      'homes_delete_home': 'Delete Home',
      'homes_delete_home_2': 'Delete Home',
      'homes_cancel_3': 'Cancel',
      'homes_delete': 'Delete',
      'homes_create_your_first_home': 'Create Your First Home',
      'homes_manage_rooms': 'Manage Rooms',
      'homes_manage_rooms_2': 'Manage Rooms',
      'homes_edit_home_3': 'Edit Home',
      'homes_edit_home_4': 'Edit Home',
      'multi_device_share_error_loading_devices_e': 'Error loading devices: $e',
      'multi_device_share_error_loading_devices_e_2': 'Error loading devices: $e',
      'multi_device_share_please_select_at_least_one_device': 'Please select at least one device',
      'multi_device_share_please_select_at_least_one_device_2': 'Please select at least one device',
      'multi_device_share_authentication_failed_e': 'Authentication failed: $e',
      'multi_device_share_authentication_failed_e_2': 'Authentication failed: $e',
      'multi_device_share_authentication_required': 'Authentication required',
      'multi_device_share_authentication_required_2': 'Authentication required',
      'multi_device_share_error_generating_qr_e': 'Error generating QR: $e',
      'multi_device_share_error_generating_qr_e_2': 'Error generating QR: $e',
      'multi_device_share_error_canceling_qr_e': 'Error canceling QR: $e',
      'multi_device_share_error_canceling_qr_e_2': 'Error canceling QR: $e',
      'multi_device_share_share_multiple_devices': 'Share Multiple Devices',
      'multi_device_share_share_multiple_devices_2': 'Share Multiple Devices',
      'multi_device_share_cancel_qr_code': 'Cancel QR Code',
      'notifications_settings_permission_denied': 'Permission Denied',
      'notifications_settings_permission_denied_2': 'Permission Denied',
      'notifications_settings_cancel': 'Cancel',
      'notifications_settings_try_again': 'Try Again',
      'notifications_settings_permission_required': 'Permission Required',
      'notifications_settings_permission_required_2': 'Permission Required',
      'notifications_settings_cancel_2': 'Cancel',
      'notifications_settings_open_settings': 'Open Settings',
      'notifications_settings_notifications': 'Notifications',
      'notifications_settings_notifications_2': 'Notifications',
      'profile_edit_profile_updated_successfully': 'Profile updated successfully!',
      'profile_edit_profile_updated_successfully_2': 'Profile updated successfully!',
      'profile_edit_error_updating_profile_e': 'Error updating profile: $e',
      'profile_edit_error_updating_profile_e_2': 'Error updating profile: $e',
      'profile_edit_edit_profile': 'Edit Profile',
      'profile_edit_edit_profile_2': 'Edit Profile',
      'profile_edit_full_name': 'Full Name',
      'profile_edit_phone_number_optional': 'Phone Number (Optional)',
      'reset_password_please_enter_the_complete_6digit_code': 'Please enter the complete 6-digit code',
      'reset_password_please_enter_the_complete_6digit_code_2': 'Please enter the complete 6-digit code',
      'reset_password_please_enter_a_new_password': 'Please enter a new password',
      'reset_password_please_enter_a_new_password_2': 'Please enter a new password',
      'reset_password_password_must_be_at_least_6_characters': 'Password must be at least 6 characters',
      'reset_password_password_must_be_at_least_6_characters_2': 'Password must be at least 6 characters',
      'reset_password_passwords_do_not_match': 'Passwords do not match',
      'reset_password_passwords_do_not_match_2': 'Passwords do not match',
      'reset_password_password_reset_successfully': 'Password reset successfully!',
      'reset_password_password_reset_successfully_2': 'Password reset successfully!',
      'reset_password_failed_to_reset_password_etostring': 'Failed to reset password: ${e.toString()}',
      'reset_password_failed_to_reset_password_etostring_2': 'Failed to reset password: ${e.toString()}',
      'reset_password_reset_code_sent_please_check_your_email': 'Reset code sent! Please check your email.',
      'reset_password_reset_code_sent_please_check_your_email_2': 'Reset code sent! Please check your email.',
      'reset_password_failed_to_resend_code_etostring': 'Failed to resend code: ${e.toString()}',
      'reset_password_failed_to_resend_code_etostring_2': 'Failed to resend code: ${e.toString()}',
      'reset_password_new_password': 'New Password',
      'reset_password_confirm_password': 'Confirm Password',
      'reset_password_reset_password': 'Reset Password',
      'rooms_failed_to_load_rooms_e': 'Failed to load rooms: $e',
      'rooms_failed_to_load_rooms_e_2': 'Failed to load rooms: $e',
      'rooms_please_enter_a_room_name': 'Please enter a room name',
      'rooms_please_enter_a_room_name_2': 'Please enter a room name',
      'rooms_room': 'Room ',
      'rooms_room_2': 'Room ',
      'rooms_failed_to_create_room_e': 'Failed to create room: $e',
      'rooms_failed_to_create_room_e_2': 'Failed to create room: $e',
      'rooms_create_new_room': 'Create New Room',
      'rooms_create_new_room_2': 'Create New Room',
      'rooms_room_name': 'Room Name',
      'rooms_eg_living_room_kitchen_etc': 'e.g., Living Room, Kitchen, etc.',
      'rooms_cancel': 'Cancel',
      'rooms_create': 'Create',
      'rooms_please_enter_a_room_name_3': 'Please enter a room name',
      'rooms_please_enter_a_room_name_4': 'Please enter a room name',
      'rooms_room_3': 'Room ',
      'rooms_room_4': 'Room ',
      'rooms_failed_to_update_room_e': 'Failed to update room: $e',
      'rooms_failed_to_update_room_e_2': 'Failed to update room: $e',
      'rooms_room_5': 'Room ',
      'rooms_room_6': 'Room ',
      'rooms_failed_to_delete_room_e': 'Failed to delete room: $e',
      'rooms_failed_to_delete_room_e_2': 'Failed to delete room: $e',
      'rooms_edit_room': 'Edit Room',
      'rooms_edit_room_2': 'Edit Room',
      'rooms_room_name_2': 'Room Name',
      'rooms_eg_living_room_kitchen_etc_2': 'e.g., Living Room, Kitchen, etc.',
      'rooms_cancel_2': 'Cancel',
      'rooms_save': 'Save',
      'rooms_delete_room': 'Delete Room',
      'rooms_delete_room_2': 'Delete Room',
      'rooms_cancel_3': 'Cancel',
      'rooms_delete': 'Delete',
      'rooms_room_background_image': 'Room Background Image',
      'rooms_room_background_image_2': 'Room Background Image',
      'rooms_failed_to_update_background_e': 'Failed to update background: $e',
      'rooms_failed_to_update_background_e_2': 'Failed to update background: $e',
      'rooms_close': 'Close',
      'rooms_change_room_icon': 'Change Room Icon',
      'rooms_change_room_icon_2': 'Change Room Icon',
      'rooms_cancel_4': 'Cancel',
      'rooms_room_icon_updated_successfully': 'Room icon updated successfully!',
      'rooms_room_icon_updated_successfully_2': 'Room icon updated successfully!',
      'rooms_failed_to_update_icon_e': 'Failed to update icon: $e',
      'rooms_failed_to_update_icon_e_2': 'Failed to update icon: $e',
      'rooms_save_2': 'Save',
      'rooms_add_your_first_room': 'Add Your First Room',
      'rooms_edit_room_3': 'Edit Room',
      'rooms_edit_room_4': 'Edit Room',
      'rooms_change_icon': 'Change Icon',
      'rooms_change_icon_2': 'Change Icon',
      'rooms_background_image': 'Background Image',
      'rooms_background_image_2': 'Background Image',
      'scan_device_qr_error_e': 'Error: $e',
      'scan_device_qr_error_e_2': 'Error: $e',
      'scan_device_qr_add_shared_device': 'Add Shared Device?',
      'scan_device_qr_add_shared_device_2': 'Add Shared Device?',
      'scan_device_qr_device_devicename': 'Device: $deviceName',
      'scan_device_qr_cancel': 'Cancel',
      'scan_device_qr_add_device': 'Add Device',
      'scan_device_qr_device_added_successfully_check_your_das': 'Device added successfully! Check your dashboard.',
      'scan_device_qr_device_added_successfully_check_your_das_2': 'Device added successfully! Check your dashboard.',
      'scan_device_qr_add_shared_devices': 'Add Shared Devices?',
      'scan_device_qr_add_shared_devices_2': 'Add Shared Devices?',
      'scan_device_qr_devicecount_devices_will_be_added': '$deviceCount device(s) will be added:',
      'scan_device_qr_cancel_2': 'Cancel',
      'scan_device_qr_add_all': 'Add All',
      'scan_device_qr_scan_device_qr_code': 'Scan Device QR Code',
      'scan_device_qr_scan_device_qr_code_2': 'Scan Device QR Code',
      'shared_devices_error_loading_shared_devices_e': 'Error loading shared devices: $e',
      'shared_devices_error_loading_shared_devices_e_2': 'Error loading shared devices: $e',
      'shared_devices_shared_with_me': 'Shared with Me',
      'shared_devices_shared_with_me_2': 'Shared with Me',
      'shared_devices_scan_qr_code': 'Scan QR Code',
      'shared_devices_scan_qr_code_2': 'Scan QR Code',
      'share_device_error_loading_data_e': 'Error loading data: $e',
      'share_device_error_loading_data_e_2': 'Error loading data: $e',
      'share_device_authentication_cancelled_or_failed': 'Authentication cancelled or failed',
      'share_device_authentication_cancelled_or_failed_2': 'Authentication cancelled or failed',
      'share_device_authentication_required_to_generate_qr_c': 'Authentication required to generate QR code',
      'share_device_authentication_required_to_generate_qr_c_2': 'Authentication required to generate QR code',
      'share_device_error_generating_qr_e': 'Error generating QR: $e',
      'share_device_error_generating_qr_e_2': 'Error generating QR: $e',
      'share_device_choose_authentication_method': 'Choose Authentication Method',
      'share_device_choose_authentication_method_2': 'Choose Authentication Method',
      'share_device_biometric': 'Biometric',
      'share_device_biometric_2': 'Biometric',
      'share_device_fingerprint_face_or_iris': 'Fingerprint, face, or iris',
      'share_device_fingerprint_face_or_iris_2': 'Fingerprint, face, or iris',
      'share_device_device_password': 'Device Password',
      'share_device_device_password_2': 'Device Password',
      'share_device_pin_password_or_pattern': 'PIN, password, or pattern',
      'share_device_pin_password_or_pattern_2': 'PIN, password, or pattern',
      'share_device_cancel': 'Cancel',
      'share_device_request_approved': 'Request approved!',
      'share_device_request_approved_2': 'Request approved!',
      'share_device_error_e': 'Error: $e',
      'share_device_error_e_2': 'Error: $e',
      'share_device_request_rejected': 'Request rejected',
      'share_device_request_rejected_2': 'Request rejected',
      'share_device_error_e_3': 'Error: $e',
      'share_device_error_e_4': 'Error: $e',
      'share_device_choose_permission_level': 'Choose Permission Level',
      'share_device_choose_permission_level_2': 'Choose Permission Level',
      'share_device_view_only': 'View Only',
      'share_device_view_only_2': 'View Only',
      'share_device_can_see_device_status': 'Can see device status',
      'share_device_can_see_device_status_2': 'Can see device status',
      'share_device_control': 'Control',
      'share_device_control_2': 'Control',
      'share_device_can_control_the_device': 'Can control the device',
      'share_device_can_control_the_device_2': 'Can control the device',
      'share_device_share_device': 'Share Device',
      'share_device_share_device_2': 'Share Device',
      'share_device_refresh': 'Refresh',
      'share_device_cancel_qr_code': 'Cancel QR Code',
      'share_device_revoke_access': 'Revoke Access?',
      'share_device_revoke_access_2': 'Revoke Access?',
      'share_device_cancel_2': 'Cancel',
      'shutter_calibration_failed_to_send_command_e': 'Failed to send command: $e',
      'shutter_calibration_failed_to_send_command_e_2': 'Failed to send command: $e',
      'shutter_calibration_please_complete_both_calibrations_first': 'Please complete both calibrations first',
      'shutter_calibration_please_complete_both_calibrations_first_2': 'Please complete both calibrations first',
      'shutter_calibration_failed_to_apply_calibration_e': 'Failed to apply calibration: $e',
      'shutter_calibration_failed_to_apply_calibration_e_2': 'Failed to apply calibration: $e',
      'shutter_calibration_failed_to_reset_calibration_e': 'Failed to reset calibration: $e',
      'shutter_calibration_failed_to_reset_calibration_e_2': 'Failed to reset calibration: $e',
      'shutter_calibration_reset': 'Reset',
      'shutter_calibration_apply_calibration': 'Apply Calibration',
      'shutter_manual_calibration_please_select_current_shutter_position': 'Please select current shutter position',
      'shutter_manual_calibration_please_select_current_shutter_position_2': 'Please select current shutter position',
      'shutter_manual_calibration_failed_to_apply_calibration_e': 'Failed to apply calibration: $e',
      'shutter_manual_calibration_failed_to_apply_calibration_e_2': 'Failed to apply calibration: $e',
      'shutter_manual_calibration_open_duration_seconds': 'Open Duration (seconds)',
      'shutter_manual_calibration_close_duration_seconds': 'Close Duration (seconds)',
      'shutter_manual_calibration_fully_closed': 'Fully Closed',
      'shutter_manual_calibration_fully_open': 'Fully Open',
      'wifi_profile_wifi_network_ssid': 'Wi-Fi Network (SSID)',
      'wifi_profile_enter_your_wifi_network_name': 'Enter your Wi-Fi network name',
      'wifi_profile_wifi_password': 'Wi-Fi Password',
      'wifi_profile_enter_your_wifi_password': 'Enter your Wi-Fi password',
      'wifi_profile_save_to_my_account_for_future_devices': 'Save to my account for future devices',
      'wifi_profile_save_to_my_account_for_future_devices_2': 'Save to my account for future devices',
      'wifi_profile_set_as_default_wifi_profile': 'Set as default Wi-Fi profile',
      'wifi_profile_set_as_default_wifi_profile_2': 'Set as default Wi-Fi profile',
      'device_selector_loading_devices': 'Loading devices...',
      'device_selector_retry': 'Retry',
      'shutter_control_failed_to_open_shutter_e': 'Failed to open shutter: $e',
      'shutter_control_failed_to_open_shutter_e_2': 'Failed to open shutter: $e',
      'shutter_control_failed_to_close_shutter_e': 'Failed to close shutter: $e',
      'shutter_control_failed_to_close_shutter_e_2': 'Failed to close shutter: $e',
      'shutter_control_failed_to_stop_shutter_e': 'Failed to stop shutter: $e',
      'shutter_control_failed_to_stop_shutter_e_2': 'Failed to stop shutter: $e',
      'shutter_control_failed_to_set_position_e': 'Failed to set position: $e',
      'shutter_control_failed_to_set_position_e_2': 'Failed to set position: $e',
      'shutter_control_shutter': 'Shutter',
      'shutter_control_curtain': 'Curtain',
      'shutter_control_none': 'None',
      'shutter_control_close': 'Close',
      'shutter_control_stop': 'Stop',
      'shutter_control_open': 'Open',
      'shutter_control_safeslidervalueround': '${safeSliderValue.round()}%',
      'background_image_picker_gallery': 'Gallery',
      'background_image_picker_camera': 'Camera',
      'background_image_picker_remove_background': 'Remove Background',
      'background_image_picker_background_image_updated_successfully': 'Background image updated successfully!',
      'background_image_picker_background_image_updated_successfully_2': 'Background image updated successfully!',
      'background_image_picker_failed_to_save_image_e': 'Failed to save image: $e',
      'background_image_picker_failed_to_save_image_e_2': 'Failed to save image: $e',
      'background_image_picker_remove_background_2': 'Remove Background',
      'background_image_picker_remove_background_3': 'Remove Background',
      'background_image_picker_cancel': 'Cancel',
      'background_image_picker_remove': 'Remove',
      'background_image_picker_background_removed_successfully': 'Background removed successfully!',
      'background_image_picker_background_removed_successfully_2': 'Background removed successfully!',

// NEW KEYS TO ADD TO 'ar' MAP:
      'activity_log_clear_activity_log': '[AR] Clear Activity Log?',
      'activity_log_clear_activity_log_2': '[AR] Clear Activity Log?',
      'activity_log_this_will_permanently_delete_all_logged_': '[AR] This will permanently delete all logged events.',
      'activity_log_this_will_permanently_delete_all_logged__2': '[AR] This will permanently delete all logged events.',
      'activity_log_cancel': 'إلغاء',
      'activity_log_clear': '[AR] Clear',
      'add_device_flow_debug_log': '[AR] Debug Log',
      'add_device_flow_log_copied_to_clipboard': '[AR] Log copied to clipboard',
      'add_device_flow_log_copied_to_clipboard_2': '[AR] Log copied to clipboard',
      'add_device_flow_copy': 'نسخ',
      'add_device_flow_share': 'مشاركة',
      'add_device_flow_wifi_network_name_ssid': '[AR] WiFi Network Name (SSID)',
      'add_device_flow_password': 'كلمة المرور',
      'add_device_flow_open_app_settings': '[AR] Open App Settings',
      'add_device_flow_password_2': 'كلمة المرور',
      'add_device_flow_save_wifi_for_future_devices': '[AR] Save WiFi for future devices',
      'add_device_flow_wrong_network': '[AR] Wrong Network?',
      'add_device_flow_wrong_network_2': '[AR] Wrong Network?',
      'add_device_flow_cancel': 'إلغاء',
      'add_device_flow_continue_anyway': '[AR] Continue Anyway',
      'add_device_flow_device_name_eg_hallway_light': '[AR] Device Name (e.g. Hallway Light)',
      'add_device_flow_edit_device_name': 'تعديل اسم الجهاز',
      'add_device_flow_edit_device_name_2': 'تعديل اسم الجهاز',
      'add_device_flow_enter_device_name': '[AR] Enter device name',
      'add_device_flow_cancel_2': 'إلغاء',
      'add_device_flow_save': 'حفظ',
      'add_device_flow_failed_to_update_device_name_e': 'فشل في التحديث',
      'add_device_flow_failed_to_update_device_name_e_2': 'فشل في التحديث',
      'add_device_flow_choose_room': '[AR] Choose Room',
      'add_device_flow_choose_room_2': '[AR] Choose Room',
      'add_device_flow_no_room': 'بدون غرفة',
      'add_device_flow_no_room_2': 'بدون غرفة',
      'add_device_flow_place_device_in_the_main_area': '[AR] Place device in the main area',
      'add_device_flow_place_device_in_the_main_area_2': '[AR] Place device in the main area',
      'add_device_flow_cancel_3': 'إلغاء',
      'add_device_flow_unable_to_move_device_please_try_again': '[AR] Unable to move device. Please try again.',
      'add_device_flow_unable_to_move_device_please_try_again_2': '[AR] Unable to move device. Please try again.',
      'add_device_flow_network_issue': '[AR] Network Issue',
      'add_device_flow_check_your_wifi_connection': '[AR] • Check your Wi-Fi connection',
      'add_device_flow_try_turning_wifi_off_and_on': '[AR] • Try turning Wi-Fi off and on',
      'add_device_flow_check_if_other_apps_can_access_the_inter': '[AR] • Check if other apps can access the internet',
      'add_device_flow_cancel_4': 'إلغاء',
      'add_device_flow_wifi_settings': '[AR] Wi-Fi Settings',
      'add_device_flow_retry': 'إعادة المحاولة',
      'add_device_flow_device_setup_error': '[AR] Device Setup Error',
      'add_device_flow_try_the_setup_process_again': '[AR] • Try the setup process again',
      'add_device_flow_reset_the_device_and_start_over': '[AR] • Reset the device and start over',
      'add_device_flow_check_if_the_device_is_already_added': '[AR] • Check if the device is already added',
      'add_device_flow_contact_support_if_the_issue_persists': '[AR] • Contact support if the issue persists',
      'add_device_flow_cancel_5': 'إلغاء',
      'add_device_flow_try_again': '[AR] Try Again',
      'add_device_flow_wifi_settings_2': '[AR] Wi-Fi Settings',
      'add_device_flow_wifi_settings_3': '[AR] Wi-Fi Settings',
      'add_timer_window_min': '[AR] $_window min',
      'devices_failed_to_load_devices_e': 'فشل في التحميل',
      'devices_failed_to_load_devices_e_2': 'فشل في التحميل',
      'devices_close': 'إغلاق',
      'devices_stop': 'إيقاف',
      'devices_open': 'فتح',
      'devices_connection_lost_please_check_your_networ': '[AR] Connection lost. Please check your network.',
      'devices_failed_to_control_shutter_etostring': 'فشل في control shutter: ${e.tostring()}',
      'devices_failed_to_control_shutter_etostring_2': 'فشل في control shutter: ${e.tostring()}',
      'devices_connection_lost_please_check_your_networ_2': '[AR] Connection lost. Please check your network.',
      'devices_failed_to_control_device_etostring': 'فشل في control device: ${e.tostring()}',
      'devices_failed_to_control_device_etostring_2': 'فشل في control device: ${e.tostring()}',
      'devices_add_device': 'إضافة الجهاز',
      'devices_add_device_2': 'إضافة الجهاز',
      'devices_hbot_device': '[AR] HBOT Device',
      'devices_hbot_device_2': '[AR] HBOT Device',
      'devices_add_hbot_device_via_wifi': 'إضافة HBOT device via Wi-Fi',
      'devices_add_hbot_device_via_wifi_2': 'إضافة HBOT device via Wi-Fi',
      'devices_cancel': 'إلغاء',
      'devices_delete_device': 'حذف الجهاز',
      'devices_delete': 'حذف',
      'devices_device': '[AR] Device ',
      'devices_device_2': '[AR] Device ',
      'devices_delete_failed': 'حذف Failed',
      'device_timers_delete_timer': 'حذف المؤقت',
      'device_timers_delete_timer_2': 'حذف المؤقت',
      'device_timers_cancel': 'إلغاء',
      'device_timers_delete': 'حذف',
      'device_timers_failed_to_update_timer_e': 'فشل في التحديث',
      'device_timers_failed_to_update_timer_e_2': 'فشل في التحديث',
      'device_timers_widgetdevicename_timers': '[AR] ${widget.device.name} Timers',
      'device_timers_add_timer': 'إضافة المؤقت',
      'feedback_send_feedback': '[AR] Send Feedback',
      'feedback_send_feedback_2': '[AR] Send Feedback',
      'feedback_send_via_email': '[AR] Send via Email',
      'feedback_send_via_whatsapp': '[AR] Send via WhatsApp',
      'help_center_help_center': 'مركز المساعدة',
      'help_center_help_center_2': 'مركز المساعدة',
      'homes_failed_to_load_homes_e': 'فشل في التحميل',
      'homes_failed_to_load_homes_e_2': 'فشل في التحميل',
      'homes_please_enter_a_home_name': 'يرجى إدخال اسم المنزل',
      'homes_please_enter_a_home_name_2': 'يرجى إدخال اسم المنزل',
      'homes_home': '[AR] Home ',
      'homes_home_2': '[AR] Home ',
      'homes_failed_to_create_home_e': 'فشل في الإنشاء',
      'homes_failed_to_create_home_e_2': 'فشل في الإنشاء',
      'homes_please_enter_a_home_name_3': 'يرجى إدخال اسم المنزل',
      'homes_please_enter_a_home_name_4': 'يرجى إدخال اسم المنزل',
      'homes_failed_to_update_home_e': 'فشل في التحديث',
      'homes_failed_to_update_home_e_2': 'فشل في التحديث',
      'homes_home_3': '[AR] Home ',
      'homes_home_4': '[AR] Home ',
      'homes_failed_to_delete_home_e': 'فشل في الحذف',
      'homes_failed_to_delete_home_e_2': 'فشل في الحذف',
      'homes_create_new_home': 'إنشاء منزل جديد',
      'homes_create_new_home_2': 'إنشاء منزل جديد',
      'homes_home_name': 'اسم المنزل',
      'homes_eg_my_house_office_etc': '[AR] e.g., My House, Office, etc.',
      'homes_cancel': 'إلغاء',
      'homes_create': 'إنشاء',
      'homes_edit_home': 'تعديل المنزل',
      'homes_edit_home_2': 'تعديل المنزل',
      'homes_home_name_2': 'اسم المنزل',
      'homes_eg_my_house_office_etc_2': '[AR] e.g., My House, Office, etc.',
      'homes_cancel_2': 'إلغاء',
      'homes_save': 'حفظ',
      'homes_delete_home': 'حذف المنزل',
      'homes_delete_home_2': 'حذف المنزل',
      'homes_cancel_3': 'إلغاء',
      'homes_delete': 'حذف',
      'homes_create_your_first_home': '[AR] Create Your First Home',
      'homes_manage_rooms': '[AR] Manage Rooms',
      'homes_manage_rooms_2': '[AR] Manage Rooms',
      'homes_edit_home_3': 'تعديل المنزل',
      'homes_edit_home_4': 'تعديل المنزل',
      'multi_device_share_error_loading_devices_e': '[AR] Error loading devices: $e',
      'multi_device_share_error_loading_devices_e_2': '[AR] Error loading devices: $e',
      'multi_device_share_please_select_at_least_one_device': '[AR] Please select at least one device',
      'multi_device_share_please_select_at_least_one_device_2': '[AR] Please select at least one device',
      'multi_device_share_authentication_failed_e': '[AR] Authentication failed: $e',
      'multi_device_share_authentication_failed_e_2': '[AR] Authentication failed: $e',
      'multi_device_share_authentication_required': '[AR] Authentication required',
      'multi_device_share_authentication_required_2': '[AR] Authentication required',
      'multi_device_share_error_generating_qr_e': '[AR] Error generating QR: $e',
      'multi_device_share_error_generating_qr_e_2': '[AR] Error generating QR: $e',
      'multi_device_share_error_canceling_qr_e': '[AR] Error canceling QR: $e',
      'multi_device_share_error_canceling_qr_e_2': '[AR] Error canceling QR: $e',
      'multi_device_share_share_multiple_devices': '[AR] Share Multiple Devices',
      'multi_device_share_share_multiple_devices_2': '[AR] Share Multiple Devices',
      'multi_device_share_cancel_qr_code': '[AR] Cancel QR Code',
      'notifications_settings_permission_denied': '[AR] Permission Denied',
      'notifications_settings_permission_denied_2': '[AR] Permission Denied',
      'notifications_settings_cancel': 'إلغاء',
      'notifications_settings_try_again': '[AR] Try Again',
      'notifications_settings_permission_required': '[AR] Permission Required',
      'notifications_settings_permission_required_2': '[AR] Permission Required',
      'notifications_settings_cancel_2': 'إلغاء',
      'notifications_settings_open_settings': '[AR] Open Settings',
      'notifications_settings_notifications': 'الإشعارات',
      'notifications_settings_notifications_2': 'الإشعارات',
      'profile_edit_profile_updated_successfully': 'تم بنجاح',
      'profile_edit_profile_updated_successfully_2': 'تم بنجاح',
      'profile_edit_error_updating_profile_e': '[AR] Error updating profile: $e',
      'profile_edit_error_updating_profile_e_2': '[AR] Error updating profile: $e',
      'profile_edit_edit_profile': 'تعديل الملف الشخصي',
      'profile_edit_edit_profile_2': 'تعديل الملف الشخصي',
      'profile_edit_full_name': '[AR] Full Name',
      'profile_edit_phone_number_optional': '[AR] Phone Number (Optional)',
      'reset_password_please_enter_the_complete_6digit_code': 'يرجى إدخال complete 6-digit code',
      'reset_password_please_enter_the_complete_6digit_code_2': 'يرجى إدخال complete 6-digit code',
      'reset_password_please_enter_a_new_password': 'يرجى إدخال new password',
      'reset_password_please_enter_a_new_password_2': 'يرجى إدخال new password',
      'reset_password_password_must_be_at_least_6_characters': '[AR] Password must be at least 6 characters',
      'reset_password_password_must_be_at_least_6_characters_2': '[AR] Password must be at least 6 characters',
      'reset_password_passwords_do_not_match': '[AR] Passwords do not match',
      'reset_password_passwords_do_not_match_2': '[AR] Passwords do not match',
      'reset_password_password_reset_successfully': '[AR] Password reset successfully!',
      'reset_password_password_reset_successfully_2': '[AR] Password reset successfully!',
      'reset_password_failed_to_reset_password_etostring': 'فشل في إعادة التعيين',
      'reset_password_failed_to_reset_password_etostring_2': 'فشل في إعادة التعيين',
      'reset_password_reset_code_sent_please_check_your_email': '[AR] Reset code sent! Please check your email.',
      'reset_password_reset_code_sent_please_check_your_email_2': '[AR] Reset code sent! Please check your email.',
      'reset_password_failed_to_resend_code_etostring': 'فشل في الإرسال',
      'reset_password_failed_to_resend_code_etostring_2': 'فشل في الإرسال',
      'reset_password_new_password': '[AR] New Password',
      'reset_password_confirm_password': '[AR] Confirm Password',
      'reset_password_reset_password': '[AR] Reset Password',
      'rooms_failed_to_load_rooms_e': 'فشل في التحميل',
      'rooms_failed_to_load_rooms_e_2': 'فشل في التحميل',
      'rooms_please_enter_a_room_name': 'يرجى إدخال اسم الغرفة',
      'rooms_please_enter_a_room_name_2': 'يرجى إدخال اسم الغرفة',
      'rooms_room': '[AR] Room ',
      'rooms_room_2': '[AR] Room ',
      'rooms_failed_to_create_room_e': 'فشل في الإنشاء',
      'rooms_failed_to_create_room_e_2': 'فشل في الإنشاء',
      'rooms_create_new_room': 'إنشاء غرفة جديدة',
      'rooms_create_new_room_2': 'إنشاء غرفة جديدة',
      'rooms_room_name': 'اسم الغرفة',
      'rooms_eg_living_room_kitchen_etc': '[AR] e.g., Living Room, Kitchen, etc.',
      'rooms_cancel': 'إلغاء',
      'rooms_create': 'إنشاء',
      'rooms_please_enter_a_room_name_3': 'يرجى إدخال اسم الغرفة',
      'rooms_please_enter_a_room_name_4': 'يرجى إدخال اسم الغرفة',
      'rooms_room_3': '[AR] Room ',
      'rooms_room_4': '[AR] Room ',
      'rooms_failed_to_update_room_e': 'فشل في التحديث',
      'rooms_failed_to_update_room_e_2': 'فشل في التحديث',
      'rooms_room_5': '[AR] Room ',
      'rooms_room_6': '[AR] Room ',
      'rooms_failed_to_delete_room_e': 'فشل في الحذف',
      'rooms_failed_to_delete_room_e_2': 'فشل في الحذف',
      'rooms_edit_room': 'تعديل الغرفة',
      'rooms_edit_room_2': 'تعديل الغرفة',
      'rooms_room_name_2': 'اسم الغرفة',
      'rooms_eg_living_room_kitchen_etc_2': '[AR] e.g., Living Room, Kitchen, etc.',
      'rooms_cancel_2': 'إلغاء',
      'rooms_save': 'حفظ',
      'rooms_delete_room': 'حذف الغرفة',
      'rooms_delete_room_2': 'حذف الغرفة',
      'rooms_cancel_3': 'إلغاء',
      'rooms_delete': 'حذف',
      'rooms_room_background_image': '[AR] Room Background Image',
      'rooms_room_background_image_2': '[AR] Room Background Image',
      'rooms_failed_to_update_background_e': 'فشل في التحديث',
      'rooms_failed_to_update_background_e_2': 'فشل في التحديث',
      'rooms_close': 'إغلاق',
      'rooms_change_room_icon': '[AR] Change Room Icon',
      'rooms_change_room_icon_2': '[AR] Change Room Icon',
      'rooms_cancel_4': 'إلغاء',
      'rooms_room_icon_updated_successfully': 'تم بنجاح',
      'rooms_room_icon_updated_successfully_2': 'تم بنجاح',
      'rooms_failed_to_update_icon_e': 'فشل في التحديث',
      'rooms_failed_to_update_icon_e_2': 'فشل في التحديث',
      'rooms_save_2': 'حفظ',
      'rooms_add_your_first_room': 'إضافة Your First Room',
      'rooms_edit_room_3': 'تعديل الغرفة',
      'rooms_edit_room_4': 'تعديل الغرفة',
      'rooms_change_icon': '[AR] Change Icon',
      'rooms_change_icon_2': '[AR] Change Icon',
      'rooms_background_image': '[AR] Background Image',
      'rooms_background_image_2': '[AR] Background Image',
      'scan_device_qr_error_e': '[AR] Error: $e',
      'scan_device_qr_error_e_2': '[AR] Error: $e',
      'scan_device_qr_add_shared_device': 'إضافة Shared Device?',
      'scan_device_qr_add_shared_device_2': 'إضافة Shared Device?',
      'scan_device_qr_device_devicename': '[AR] Device: $deviceName',
      'scan_device_qr_cancel': 'إلغاء',
      'scan_device_qr_add_device': 'إضافة الجهاز',
      'scan_device_qr_device_added_successfully_check_your_das': '[AR] Device added successfully! Check your dashboard.',
      'scan_device_qr_device_added_successfully_check_your_das_2': '[AR] Device added successfully! Check your dashboard.',
      'scan_device_qr_add_shared_devices': 'إضافة Shared Devices?',
      'scan_device_qr_add_shared_devices_2': 'إضافة Shared Devices?',
      'scan_device_qr_devicecount_devices_will_be_added': '[AR] $deviceCount device(s) will be added:',
      'scan_device_qr_cancel_2': 'إلغاء',
      'scan_device_qr_add_all': 'إضافة All',
      'scan_device_qr_scan_device_qr_code': '[AR] Scan Device QR Code',
      'scan_device_qr_scan_device_qr_code_2': '[AR] Scan Device QR Code',
      'shared_devices_error_loading_shared_devices_e': '[AR] Error loading shared devices: $e',
      'shared_devices_error_loading_shared_devices_e_2': '[AR] Error loading shared devices: $e',
      'shared_devices_shared_with_me': 'مشترك معي',
      'shared_devices_shared_with_me_2': 'مشترك معي',
      'shared_devices_scan_qr_code': '[AR] Scan QR Code',
      'shared_devices_scan_qr_code_2': '[AR] Scan QR Code',
      'share_device_error_loading_data_e': '[AR] Error loading data: $e',
      'share_device_error_loading_data_e_2': '[AR] Error loading data: $e',
      'share_device_authentication_cancelled_or_failed': '[AR] Authentication cancelled or failed',
      'share_device_authentication_cancelled_or_failed_2': '[AR] Authentication cancelled or failed',
      'share_device_authentication_required_to_generate_qr_c': '[AR] Authentication required to generate QR code',
      'share_device_authentication_required_to_generate_qr_c_2': '[AR] Authentication required to generate QR code',
      'share_device_error_generating_qr_e': '[AR] Error generating QR: $e',
      'share_device_error_generating_qr_e_2': '[AR] Error generating QR: $e',
      'share_device_choose_authentication_method': '[AR] Choose Authentication Method',
      'share_device_choose_authentication_method_2': '[AR] Choose Authentication Method',
      'share_device_biometric': '[AR] Biometric',
      'share_device_biometric_2': '[AR] Biometric',
      'share_device_fingerprint_face_or_iris': '[AR] Fingerprint, face, or iris',
      'share_device_fingerprint_face_or_iris_2': '[AR] Fingerprint, face, or iris',
      'share_device_device_password': '[AR] Device Password',
      'share_device_device_password_2': '[AR] Device Password',
      'share_device_pin_password_or_pattern': '[AR] PIN, password, or pattern',
      'share_device_pin_password_or_pattern_2': '[AR] PIN, password, or pattern',
      'share_device_cancel': 'إلغاء',
      'share_device_request_approved': '[AR] Request approved!',
      'share_device_request_approved_2': '[AR] Request approved!',
      'share_device_error_e': '[AR] Error: $e',
      'share_device_error_e_2': '[AR] Error: $e',
      'share_device_request_rejected': '[AR] Request rejected',
      'share_device_request_rejected_2': '[AR] Request rejected',
      'share_device_error_e_3': '[AR] Error: $e',
      'share_device_error_e_4': '[AR] Error: $e',
      'share_device_choose_permission_level': '[AR] Choose Permission Level',
      'share_device_choose_permission_level_2': '[AR] Choose Permission Level',
      'share_device_view_only': 'عرض فقط',
      'share_device_view_only_2': 'عرض فقط',
      'share_device_can_see_device_status': '[AR] Can see device status',
      'share_device_can_see_device_status_2': '[AR] Can see device status',
      'share_device_control': 'تحكم',
      'share_device_control_2': 'تحكم',
      'share_device_can_control_the_device': '[AR] Can control the device',
      'share_device_can_control_the_device_2': '[AR] Can control the device',
      'share_device_share_device': 'مشاركة الجهاز',
      'share_device_share_device_2': 'مشاركة الجهاز',
      'share_device_refresh': 'تحديث',
      'share_device_cancel_qr_code': '[AR] Cancel QR Code',
      'share_device_revoke_access': '[AR] Revoke Access?',
      'share_device_revoke_access_2': '[AR] Revoke Access?',
      'share_device_cancel_2': 'إلغاء',
      'shutter_calibration_failed_to_send_command_e': 'فشل في الإرسال',
      'shutter_calibration_failed_to_send_command_e_2': 'فشل في الإرسال',
      'shutter_calibration_please_complete_both_calibrations_first': '[AR] Please complete both calibrations first',
      'shutter_calibration_please_complete_both_calibrations_first_2': '[AR] Please complete both calibrations first',
      'shutter_calibration_failed_to_apply_calibration_e': 'فشل في apply calibration',
      'shutter_calibration_failed_to_apply_calibration_e_2': 'فشل في apply calibration',
      'shutter_calibration_failed_to_reset_calibration_e': 'فشل في إعادة التعيين',
      'shutter_calibration_failed_to_reset_calibration_e_2': 'فشل في إعادة التعيين',
      'shutter_calibration_reset': 'إعادة تعيين',
      'shutter_calibration_apply_calibration': '[AR] Apply Calibration',
      'shutter_manual_calibration_please_select_current_shutter_position': '[AR] Please select current shutter position',
      'shutter_manual_calibration_please_select_current_shutter_position_2': '[AR] Please select current shutter position',
      'shutter_manual_calibration_failed_to_apply_calibration_e': 'فشل في apply calibration',
      'shutter_manual_calibration_failed_to_apply_calibration_e_2': 'فشل في apply calibration',
      'shutter_manual_calibration_open_duration_seconds': '[AR] Open Duration (seconds)',
      'shutter_manual_calibration_close_duration_seconds': '[AR] Close Duration (seconds)',
      'shutter_manual_calibration_fully_closed': '[AR] Fully Closed',
      'shutter_manual_calibration_fully_open': '[AR] Fully Open',
      'wifi_profile_wifi_network_ssid': '[AR] Wi-Fi Network (SSID)',
      'wifi_profile_enter_your_wifi_network_name': '[AR] Enter your Wi-Fi network name',
      'wifi_profile_wifi_password': '[AR] Wi-Fi Password',
      'wifi_profile_enter_your_wifi_password': '[AR] Enter your Wi-Fi password',
      'wifi_profile_save_to_my_account_for_future_devices': '[AR] Save to my account for future devices',
      'wifi_profile_save_to_my_account_for_future_devices_2': '[AR] Save to my account for future devices',
      'wifi_profile_set_as_default_wifi_profile': '[AR] Set as default Wi-Fi profile',
      'wifi_profile_set_as_default_wifi_profile_2': '[AR] Set as default Wi-Fi profile',
      'device_selector_loading_devices': '[AR] Loading devices...',
      'device_selector_retry': 'إعادة المحاولة',
      'shutter_control_failed_to_open_shutter_e': 'فشل في open shutter',
      'shutter_control_failed_to_open_shutter_e_2': 'فشل في open shutter',
      'shutter_control_failed_to_close_shutter_e': 'فشل في close shutter',
      'shutter_control_failed_to_close_shutter_e_2': 'فشل في close shutter',
      'shutter_control_failed_to_stop_shutter_e': 'فشل في stop shutter',
      'shutter_control_failed_to_stop_shutter_e_2': 'فشل في stop shutter',
      'shutter_control_failed_to_set_position_e': 'فشل في set position',
      'shutter_control_failed_to_set_position_e_2': 'فشل في set position',
      'shutter_control_shutter': 'مصراع',
      'shutter_control_curtain': '[AR] Curtain',
      'shutter_control_none': '[AR] None',
      'shutter_control_close': 'إغلاق',
      'shutter_control_stop': 'إيقاف',
      'shutter_control_open': 'فتح',
      'shutter_control_safeslidervalueround': '[AR] ${safeSliderValue.round()}%',
      'background_image_picker_gallery': '[AR] Gallery',
      'background_image_picker_camera': '[AR] Camera',
      'background_image_picker_remove_background': '[AR] Remove Background',
      'background_image_picker_background_image_updated_successfully': 'تم بنجاح',
      'background_image_picker_background_image_updated_successfully_2': 'تم بنجاح',
      'background_image_picker_failed_to_save_image_e': 'فشل في الحفظ',
      'background_image_picker_failed_to_save_image_e_2': 'فشل في الحفظ',
      'background_image_picker_remove_background_2': '[AR] Remove Background',
      'background_image_picker_remove_background_3': '[AR] Remove Background',
      'background_image_picker_cancel': 'إلغاء',
      'background_image_picker_remove': 'إزالة',
      'background_image_picker_background_removed_successfully': 'تم بنجاح',
      'background_image_picker_background_removed_successfully_2': 'تم بنجاح',
